import Head from 'next/head'
import { baseUrl } from '../../utils'
import { useRouter } from 'next/router'
import axios from 'axios'

export default function Posts({ data }) {
  const router = useRouter()

  function seeDetail(id) {
    router.push(`posts/${id}`)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-content">
        {data && data.map((post) => (
          <div className="card mt-2" key={post.id} onClick={() => seeDetail(post.id)}>
            <div className="card-body">
              <h5 className="card-title">{post.title}</h5>
              <div className="card-text">
                {post.description}
              </div>
            </div>
          </div>
        ))}

        <div className="text-muted">No data found</div> 
      </div>
    </div>
  )
}

export async function getStaticProps(context) {
  const res = await fetch(`${baseUrl}/api/posts`)
  const data = await res.json()
  if (!data) {
    return {
      notFound: true,
    }
  }
  return {
    props: { data },
  }
}